//
//  Currency.swift
//  CurrencyConverter
//
//  Created by MasterBi on 11/01/2025.
//

/// Supported currencies with ISO 4217 codes
///
/// # Features
/// - ISO currency codes
/// - Localized currency names
/// - Codable support
/// - Case iteration
///
/// # Usage Example
/// ```swift
/// let usd = Currency.USD
/// print(usd.name) // "United States Dollar"
/// print(usd.rawValue) // "USD"
/// ```
enum Currency: String, CaseIterable, Decodable {
	case AED = "AED"
	case AFN = "AFN"
	case ALL = "ALL"
	case AMD = "AMD"
	case ANG = "ANG"
	case AOA = "AOA"
	case ARS = "ARS"
	case AUD = "AUD"
	case AWG = "AWG"
	case AZN = "AZN"
	case BAM = "BAM"
	case BBD = "BBD"
	case BDT = "BDT"
	case BGN = "BGN"
	case BHD = "BHD"
	case BIF = "BIF"
	case BMD = "BMD"
	case BND = "BND"
	case BOB = "BOB"
	case BRL = "BRL"
	case BSD = "BSD"
	case BTC = "BTC"
	case BTN = "BTN"
	case BWP = "BWP"
	case BYN = "BYN"
	case BZD = "BZD"
	case CAD = "CAD"
	case CDF = "CDF"
	case CHF = "CHF"
	case CLF = "CLF"
	case CLP = "CLP"
	case CNH = "CNH"
	case CNY = "CNY"
	case COP = "COP"
	case CRC = "CRC"
	case CUC = "CUC"
	case CUP = "CUP"
	case CVE = "CVE"
	case CZK = "CZK"
	case DJF = "DJF"
	case DKK = "DKK"
	case DOP = "DOP"
	case DZD = "DZD"
	case EGP = "EGP"
	case ERN = "ERN"
	case ETB = "ETB"
	case EUR = "EUR"
	case FJD = "FJD"
	case FKP = "FKP"
	case GBP = "GBP"
	case GEL = "GEL"
	case GGP = "GGP"
	case GHS = "GHS"
	case GIP = "GIP"
	case GMD = "GMD"
	case GNF = "GNF"
	case GTQ = "GTQ"
	case GYD = "GYD"
	case HKD = "HKD"
	case HNL = "HNL"
	case HRK = "HRK"
	case HTG = "HTG"
	case HUF = "HUF"
	case IDR = "IDR"
	case ILS = "ILS"
	case IMP = "IMP"
	case INR = "INR"
	case IQD = "IQD"
	case IRR = "IRR"
	case ISK = "ISK"
	case JEP = "JEP"
	case JMD = "JMD"
	case JOD = "JOD"
	case JPY = "JPY"
	case KES = "KES"
	case KGS = "KGS"
	case KHR = "KHR"
	case KMF = "KMF"
	case KPW = "KPW"
	case KRW = "KRW"
	case KWD = "KWD"
	case KYD = "KYD"
	case KZT = "KZT"
	case LAK = "LAK"
	case LBP = "LBP"
	case LKR = "LKR"
	case LRD = "LRD"
	case LSL = "LSL"
	case LYD = "LYD"
	case MAD = "MAD"
	case MDL = "MDL"
	case MGA = "MGA"
	case MKD = "MKD"
	case MMK = "MMK"
	case MNT = "MNT"
	case MOP = "MOP"
	case MRU = "MRU"
	case MUR = "MUR"
	case MVR = "MVR"
	case MWK = "MWK"
	case MXN = "MXN"
	case MYR = "MYR"
	case MZN = "MZN"
	case NAD = "NAD"
	case NGN = "NGN"
	case NIO = "NIO"
	case NOK = "NOK"
	case NPR = "NPR"
	case NZD = "NZD"
	case OMR = "OMR"
	case PAB = "PAB"
	case PEN = "PEN"
	case PGK = "PGK"
	case PHP = "PHP"
	case PKR = "PKR"
	case PLN = "PLN"
	case PYG = "PYG"
	case QAR = "QAR"
	case RON = "RON"
	case RSD = "RSD"
	case RUB = "RUB"
	case RWF = "RWF"
	case SAR = "SAR"
	case SBD = "SBD"
	case SCR = "SCR"
	case SDG = "SDG"
	case SEK = "SEK"
	case SGD = "SGD"
	case SHP = "SHP"
	case SLL = "SLL"
	case SOS = "SOS"
	case SRD = "SRD"
	case SSP = "SSP"
	case STD = "STD"
	case STN = "STN"
	case SVC = "SVC"
	case SYP = "SYP"
	case SZL = "SZL"
	case THB = "THB"
	case TJS = "TJS"
	case TMT = "TMT"
	case TND = "TND"
	case TOP = "TOP"
	case TRY = "TRY"
	case TTD = "TTD"
	case TWD = "TWD"
	case TZS = "TZS"
	case UAH = "UAH"
	case UGX = "UGX"
	case USD = "USD"
	case UYU = "UYU"
	case UZS = "UZS"
	case VES = "VES"
	case VND = "VND"
	case VUV = "VUV"
	case WST = "WST"
	case XAF = "XAF"
	case XAG = "XAG"
	case XAU = "XAU"
	case XCD = "XCD"
	case XDR = "XDR"
	case XOF = "XOF"
	case XPD = "XPD"
	case XPF = "XPF"
	case XPT = "XPT"
	case YER = "YER"
	case ZAR = "ZAR"
	case ZMW = "ZMW"
	case ZWL = "ZWL"
	
    /// Provides localized currency names
    ///
    /// # Returns
    /// Full currency name in English
	var name: String {
		switch self {
				case .AED: return "United Arab Emirates Dirham"
				case .AFN: return "Afghan Afghani"
				case .ALL: return "Albanian Lek"
				case .AMD: return "Armenian Dram"
				case .ANG: return "Netherlands Antillean Guilder"
				case .AOA: return "Angolan Kwanza"
				case .ARS: return "Argentine Peso"
				case .AUD: return "Australian Dollar"
				case .AWG: return "Aruban Florin"
				case .AZN: return "Azerbai"
				case .BAM: return "Bosnia-Herzegovina Convertible Mark"
				case .BBD: return "Barbadian Dollar"
				case .BDT: return "Bangladeshi Taka"
				case .BGN: return "Bulgarian Lev"
				case .BHD: return "Bahraini Dinar"
				case .BIF: return "Burundian Franc"
				case .BMD: return "Bermudian Dollar"
				case .BND: return "Brunei Dollar"
				case .BOB: return "Bolivian Boliviano"
				case .BRL: return "Brazilian Real"
				case .BSD: return "Bahamian Dollar"
				case .BTC: return "Bitcoin"
				case .BTN: return "Bhutanese Ngultrum"
				case .BWP: return "Botswanan Pula"
				case .BYN: return "Belarusian Ruble"
				case .BZD: return "Belize Dollar"
				case .CAD: return "Canadian Dollar"
				case .CDF: return "Congolese Franc"
				case .CHF: return "Swiss Franc"
				case .CLF: return "Chilean Unit of Account (UF)"
				case .CLP: return "Chilean Peso"
				case .CNH: return "Chinese Yuan (Offshore)"
				case .CNY: return "Chinese Yuan"
				case .COP: return "Colombian Peso"
				case .CRC: return "Costa Rican Colón"
				case .CUC: return "Cuban Convertible Peso"
				case .CUP: return "Cuban Peso"
				case .CVE: return "Cape Verdean Escudo"
				case .CZK: return "Czech Republic Koruna"
				case .DJF: return "Djiboutian Franc"
				case .DKK: return "Danish Krone"
				case .DOP: return "Dominican Peso"
				case .DZD: return "Algerian Dinar"
				case .EGP: return "Egyptian Pound"
				case .ERN: return "Eritrean Nakfa"
				case .ETB: return "Ethiopian Birr"
				case .EUR: return "Euro"
				case .FJD: return "Fijian Dollar"
				case .FKP: return "Falkland Islands Pound"
				case .GBP: return "British Pound Sterling"
				case .GEL: return "Georgian Lari"
				case .GGP: return "Guernsey Pound"
				case .GHS: return "Ghanaian Cedi"
				case .GIP: return "Gibraltar Pound"
				case .GMD: return "Gambian Dalasi"
				case .GNF: return "Guinean Franc"
				case .GTQ: return "Guatemalan Quetzal"
				case .GYD: return "Guyanaese Dollar"
				case .HKD: return "Hong Kong Dollar"
				case .HNL: return "Honduran Lempira"
				case .HRK: return "Croatian Kuna"
				case .HTG: return "Haitian Gourde"
				case .HUF: return "Hungarian Forint"
				case .IDR: return "Indonesian Rupiah"
				case .ILS: return "Israeli New Sheqel"
				case .IMP: return "Isle of Man Pound"
				case .INR: return "Indian Rupee"
				case .IQD: return "Iraqi Dinar"
				case .IRR: return "Iranian Rial"
				case .ISK: return "Icelandic Króna"
				case .JEP: return "Jersey Pound"
				case .JMD: return "Jamaican Dollar"
				case .JOD: return "Jordanian Dinar"
				case .JPY: return "Japanese Yen"
				case .KES: return "Kenyan Shilling"
				case .KGS: return "Kyrgystani Som"
				case .KHR: return "Cambodian Riel"
				case .KMF: return "Comorian Franc"
				case .KPW: return "North Korean Won"
				case .KRW: return "South Korean Won"
				case .KWD: return "Kuwaiti Dinar"
				case .KYD: return "Cayman Islands Dollar"
				case .KZT: return "Kazakhstani Tenge"
				case .LAK: return "Laotian Kip"
				case .LBP: return "Lebanese Pound"
				case .LKR: return "Sri Lankan Rupee"
				case .LRD: return "Liberian Dollar"
				case .LSL: return "Lesotho Loti"
				case .LYD: return "Libyan Dinar"
				case .MAD: return "Moroccan Dirham"
				case .MDL: return "Moldovan Leu"
				case .MGA: return "Malagasy Ariary"
				case .MKD: return "Macedonian Denar"
				case .MMK: return "Burmese Kyat"
				case .MNT: return "Mongolian Tugrik"
				case .MOP: return "Macanese Pataca"
				case .MRU: return "Mauritanian Ouguiya"
				case .MUR: return "Mauritian Rupee"
				case .MVR: return "Maldivian Rufiyaa"
				case .MWK: return "Malawian Kwacha"
				case .MXN: return "Mexican Peso"
				case .MYR: return "Malaysian Ringgit"
				case .MZN: return "Mozambican Metical"
				case .NAD: return "Namibian Dollar"
				case .NGN: return "Nigerian Naira"
				case .NIO: return "Nicaraguan Córdoba"
				case .NOK: return "Norwegian Krone"
				case .NPR: return "Nepalese Rupee"
				case .NZD: return "New Zealand Dollar"
				case .OMR: return "Omani Rial"
				case .PAB: return "Panamanian Balboa"
				case .PEN: return "Peruvian Nuevo Sol"
				case .PGK: return "Papua New Guinean Kina"
				case .PHP: return "Philippine Peso"
				case .PKR: return "Pakistani Rupee"
				case .PLN: return "Polish Zloty"
				case .PYG: return "Paraguayan Guarani"
				case .QAR: return "Qatari Rial"
				case .RON: return "Romanian Leu"
				case .RSD: return "Serbian Dinar"
				case .RUB: return "Russian Ruble"
				case .RWF: return "Rwandan Franc"
				case .SAR: return "Saudi Riyal"
				case .SBD: return "Solomon Islands Dollar"
				case .SCR: return "Seychellois Rupee"
				case .SDG: return "Sudanese Pound"
				case .SEK: return "Swedish Krona"
				case .SGD: return "Singapore Dollar"
				case .SHP: return "Saint Helena Pound"
				case .SLL: return "Sierra Leonean Leone"
				case .SOS: return "Somali Shilling"
				case .SRD: return "Surinamese Dollar"
				case .SSP: return "South Sudanese Pound"
				case .STD: return "São Tomé and Príncipe Dobra"
				case .STN: return "São Tomé and Príncipe Dobra (2018)"
				case .SVC: return "Salvadoran Colón"
				case .SYP: return "Syrian Pound"
				case .SZL: return "Swazi Lilangeni"
				case .THB: return "Thai Baht"
				case .TJS: return "Tajikistani Somoni"
				case .TMT: return "Turkmenistani Manat"
				case .TND: return "Tunisian Dinar"
				case .TOP: return "Tongan Pa'anga"
				case .TRY: return "Turkish Lira"
				case .TTD: return "Trinidad and Tobago Dollar"
				case .TWD: return "New Taiwan Dollar"
				case .TZS: return "Tanzanian Shilling"
				case .UAH: return "Ukrainian Hryvnia"
				case .UGX: return "Ugandan Shilling"
				case .USD: return "United States Dollar"
				case .UYU: return "Uruguayan Peso"
				case .UZS: return "Uzbekistan Som"
				case .VES: return "Venezuelan Bolívar"
				case .VND: return "Vietnamese Dong"
				case .VUV: return "Vanuatu Vatu"
				case .WST: return "Samoan Tala"
				case .XAF: return "CFA Franc BEAC"
				case .XAG: return "Silver Ounce"
				case .XAU: return "Gold Ounce"
				case .XCD: return "East Caribbean Dollar"
				case .XDR: return "Special Drawing Rights"
				case .XOF: return "CFA Franc BCEAO"
				case .XPD: return "Palladium Ounce"
				case .XPF: return "CFP Franc"
				case .XPT: return "Platinum Ounce"
				case .YER: return "Yemeni Rial"
				case .ZAR: return "South African Rand"
				case .ZMW: return "Zimbabwean Kwacha"
				case .ZWL: return "Zimbabwean Dollar"
		}
	}
}
